apiVersion: v1
kind: Pod
metadata:
  name: ca-gen
  namespace: skycluster-system
spec:
  restartPolicy: Never
  containers:
    - name: ca-gen
      image: etesami/ca-gen:70ee90e78657d6167691ee3228ae5dd0fdce4dd8
      # command: ["sh", "-c", "echo $MY_VAR"]
      env:
        - name: POD_NAMESPACE
          value: "skycluster-system"
