apiVersion: v1
kind: Pod
metadata:
  name: ca-signer
  namespace: skycluster-system
spec:
  containers:
  - name: ca-signer
    image: etesami/ca-signer:35217a7
    env:
    - name: CA_SECRET_NAME
      value: skycluster-self-ca
    - name: OUTPUT_SECRET_NAME
      value: headscale-cert
    - name: NAMESPACE
      value: skycluster-system
    - name: CERT_COMMON_NAME
      value: "skycluster.local"
    - name: CERT_SANS
      value: "DNS:host.docker.internal,DNS:skycluster.local,IP:172.18.0.3,IP:0.0.0.0"
  restartPolicy: Never
  serviceAccountName: skycluster-sva