# monitoring-values.yaml
# Minimal values for demo: instruct Prometheus operator to watch perf-app namespace
prometheus:
  prometheusSpec:
    # Allow Prometheus to discover ServiceMonitors in the redis-app namespace
    serviceMonitorNamespaceSelector: {}
      # matchLabels:
      #   app: redis-app
    # Empty selector means "select all" ServiceMonitors in the selected namespaces
    serviceMonitorSelector: {}

alertmanager:
  enabled: false

grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin        # replace for production
  service:
    type: ClusterIP